apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo1
spec:
  selector:
    matchLabels:
      app: zoo1
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo1
    spec:
      containers:
      - name: zoo1
        image: confluentinc/cp-zookeeper:latest
        env:
        - name: "ZOOKEEPER_SERVER_ID"
          value: "1"
        - name: "ZOOKEEPER_CLIENT_PORT"
          value: "2181"
        - name: "ZOOKEEPER_SERVERS"
          value: "0.0.0.0:2888:3888;zoo2:2888:3888;zoo3:2888:3888"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo2
spec:
  selector:
    matchLabels:
      app: zoo2
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo2
    spec:
      containers:
        - name: zoo2
          image: confluentinc/cp-zookeeper:latest
          env:
          - name: "ZOOKEEPER_SERVER_ID"
            value: "2"
          - name: "ZOOKEEPER_CLIENT_PORT"
            value: "2181"
          - name: "ZOOKEEPER_SERVERS"
            value: "zoo1:2888:3888;0.0.0.0:2888:3888;zoo3:2888:3888"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoo3
spec:
  selector:
    matchLabels:
      app: zoo3
  replicas: 1
  template:
    metadata:
      labels:
        app: zoo3
    spec:
      containers:
        - name: zoo3
          image: confluentinc/cp-zookeeper:latest
          env:
          - name: "ZOOKEEPER_SERVER_ID"
            value: "3"
          - name: "ZOOKEEPER_CLIENT_PORT"
            value: "2181"
          - name: "ZOOKEEPER_SERVERS"
            value: "zoo1:2888:3888;zoo2:2888:3888;0.0.0.0:2888:3888"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka1
spec:
  selector:
    matchLabels:
      app: kafka1
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:latest
        env:
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: "KAFKA_BROKER_ID"
          value: "1"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://52.231.73.41:9092"
        - name: "KAFKA_LISTENERS"
          value: "PLAINTEXT://0.0.0.0:9092"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka2
spec:
  selector:
    matchLabels:
      app: kafka2
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      containers:
      - name: kafka2
        image: confluentinc/cp-kafka:latest
        env:
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: "KAFKA_BROKER_ID"
          value: "2"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://52.141.61.20:9092"
        - name: "KAFKA_LISTENERS"
          value: "PLAINTEXT://0.0.0.0:9092"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka3
spec:
  selector:
    matchLabels:
      app: kafka3
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      containers:
      - name: kafka3
        image: confluentinc/cp-kafka:latest
        env:
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          value: "zoo1:2181,zoo2:2181,zoo3:2181"
        - name: "KAFKA_BROKER_ID"
          value: "3"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          value: "PLAINTEXT://52.141.61.158:9092"
        - name: "KAFKA_LISTENERS"
          value: "PLAINTEXT://0.0.0.0:9092"