---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
spec:
  type: ClusterIP
  selector:
    app: zoo1
  ports:
  - name : port1
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name : port2
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name : port3
    protocol: TCP
    port: 3888
    targetPort: 3888

---

apiVersion: v1
kind: Service
metadata:
  name: zoo2
spec:
  type: ClusterIP
  selector:
    app: zoo2
  ports:
  - name: port1
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name: port2
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: port3
    protocol: TCP
    port: 3888
    targetPort: 3888

---

apiVersion: v1
kind: Service
metadata:
  name: zoo3
spec:
  type: ClusterIP
  selector:
    app: zoo3
  ports:
  - name: port1
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name: port2
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: port3
    protocol: TCP
    port: 3888
    targetPort: 3888

---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
spec:
  type: LoadBalancer
  selector:
    app: kafka1
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: kafka2
spec:
  type: LoadBalancer
  selector:
    app: kafka2
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: kafka3
spec:
  type: LoadBalancer
  selector:
    app: kafka3
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092