spring:
  application:
    name: kafka-test
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    hikari:
      leak-detection-threshold: 1000

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  kafka:
    bootstrap-servers: 52.231.73.41:9092,52.141.61.20:9092,52.141.61.158:9092